---
name: integration

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  integration:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        include:
          - test_type: unix
          - test_type: tcp
          - test_type: tls
    env:
      TEST_TYPE: ${{ matrix.test_type }}
    steps:
      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: "1.26.x"
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Start containers
        working-directory: integration
        run: docker compose -f docker-compose-$TEST_TYPE.yml up --build --detach
      - name: run integration test
        working-directory: integration
        run: go test -v --tags=integration
      - name: Stop containers
        if: always()
        working-directory: integration
        run: docker compose -f docker-compose-$TEST_TYPE.yml down
