name: build-unbound_explorer
on:
  create:
    tags:
      - ^v\d{1,}\.\d{1,}\.\d{1,}$

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      CONTAINER_IMAGE: ghcr.io/${{github.repository}}
      DOCKER_VERSION: ${{github.ref_name}}
      DOCKER_TARGET_PLATFORM: linux/arm64,linux/amd64
    steps:
      -
        id: checkout
        name: Checkout the code
        uses: actions/checkout@v2
      -
        id: install-qemu
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        id: install-buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      -
        id: login-registry
        name: Log into registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} \
            --password-stdin
      -
        id: build
        name: Build
        run: |
          docker build \
          --platform ${DOCKER_TARGET_PLATFORM} \
          --tag ${CONTAINER_IMAGE}:${DOCKER_VERSION} \
          --push \
          .
